### ISSUE TITLE
MAJOR TODO: Overhaul Image Picker

### ISSUE THREAD

**Issue by kjg531** [EventHi/EventHi#5]
**Problem:**
The weak point of the entire create form is 100% the Image Picker. IMHO, this needs to be overhauled in react as well as the rest of the create form.

**Intended Behavior:**
- [ ] when host is personal account show personal images, and if organization is host show organization images.
- [ ] when validation errors reselect images
- [ ] when in edit for preselect images
- [ ] add DropZone modal
- [ ] add photo to pagination after added
- [ ] use gallery format and when LightBox comes up have 2 add buttons in window
- [ ] on validation error, save selections
- [ ] limit 8 photos per event, and 80 per user/organization

**Suggested Course of Action:**
I'm going to go ahead and assign this to me, but I will definitely need some assistance from @aaj on this one. More deliberation needs to be done on the solution for this issue. On 7/22 i'm leaning towards a reactJS solution for most, if not all of the create form.

**Comment by kjg531** [comment]
Closing Pre-React Issue
